[program:php-fpm]
command=php-fpm -y /app/deploy/coolify/php-fpm.conf -F
autostart=true
autorestart=true
startsecs=1
stopsignal=QUIT
stopwaitsecs=30
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
