[program:scheduler]
command=php /app/artisan schedule:work
directory=/app
user=www-data
autostart=true
autorestart=true
numprocs=1
startsecs=1
stopasgroup=true
killasgroup=true
stopsignal=TERM
stopwaitsecs=60
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
